$(document).ready(function(){
    $('.main__slider').slick({
        dots:true,
    });
    $('.clients__slider').slick({
        dots:true,
    });
    $('.reviews__slider').slick({
        dots:true,
    });
});